### ISSUE TITLE
CT PhetioObject baseline must equal baseline schema to ensure that baseline changes are intentional

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/states-of-matter-basics#25]
```
states-of-matter-basics : phet-io-fuzz : require.js : load
https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/states-of-matter-basics/states-of-matter-basics_en.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&brand=phet-io&phetioStandalone&ea&fuzz&memoryLimit=1000
Query: brand=phet-io&phetioStandalone&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: PhET-iO API error:
2. Registered PhetioObject baseline must equal baseline schema to ensure that baseline changes are intentional.
Error: Assertion failed: PhET-iO API error:
2. Registered PhetioObject baseline must equal baseline schema to ensure that baseline changes are intentional.
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/assert/js/assert.js?bust=1584926582760:22:13)
    at PhetioAPIValidation.assertAPIError (https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/tandem/js/phetioAPIValidation.js:277:15)
    at PhetioAPIValidation.onSimStarted (https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/tandem/js/phetioAPIValidation.js:115:14)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/phet-io/js/phetioEngine.js:158:27
    at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/axon/js/TinyEmitter.js:65:53)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/axon/js/Emitter.js:33:29
    at Emitter.execute (https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/axon/js/Action.js:224:18)
    at Emitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/axon/js/Emitter.js:58:19)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/joist/js/Sim.js:842:48
id: Bayes Chrome
Approximately 3/22/2020, 6:33:45 PM
states-of-matter-basics : phet-io-fuzz : require.js : load
https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/states-of-matter-basics/states-of-matter-basics_en.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&brand=phet-io&phetioStandalone&ea&fuzz&memoryLimit=1000
Query: brand=phet-io&phetioStandalone&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: PhET-iO API error:
2. Registered PhetioObject baseline must equal baseline schema to ensure that baseline changes are intentional.
Error: Assertion failed: PhET-iO API error:
2. Registered PhetioObject baseline must equal baseline schema to ensure that baseline changes are intentional.
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/assert/js/assert.js?bust=1584945674210:22:13)
    at PhetioAPIValidation.assertAPIError (https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/tandem/js/phetioAPIValidation.js:277:15)
    at PhetioAPIValidation.onSimStarted (https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/tandem/js/phetioAPIValidation.js:115:14)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/phet-io/js/phetioEngine.js:158:27
    at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/axon/js/TinyEmitter.js:65:53)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/axon/js/Emitter.js:33:29
    at Emitter.execute (https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/axon/js/Action.js:224:18)
    at Emitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/axon/js/Emitter.js:58:19)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/joist/js/Sim.js:842:48
id: Bayes Chrome
Approximately 3/22/2020, 6:33:45 PM
states-of-matter-basics : phet-io-fuzz : require.js : load
https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/states-of-matter-basics/states-of-matter-basics_en.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&brand=phet-io&phetioStandalone&ea&fuzz&memoryLimit=1000
Query: brand=phet-io&phetioStandalone&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: PhET-iO API error:
2. Registered PhetioObject baseline must equal baseline schema to ensure that baseline changes are intentional.
Error: Assertion failed: PhET-iO API error:
2. Registered PhetioObject baseline must equal baseline schema to ensure that baseline changes are intentional.
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/assert/js/assert.js?bust=1584966797562:22:13)
    at PhetioAPIValidation.assertAPIError (https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/tandem/js/phetioAPIValidation.js:277:15)
    at PhetioAPIValidation.onSimStarted (https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/tandem/js/phetioAPIValidation.js:115:14)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/phet-io/js/phetioEngine.js:158:27
    at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/axon/js/TinyEmitter.js:65:53)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/axon/js/Emitter.js:33:29
    at Emitter.execute (https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/axon/js/Action.js:224:18)
    at Emitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/axon/js/Emitter.js:58:19)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/joist/js/Sim.js:842:48
id: Bayes Chrome
Approximately 3/22/2020, 6:33:45 PM
states-of-matter-basics : phet-io-fuzz : require.js : run
https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/states-of-matter-basics/states-of-matter-basics_en.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&brand=phet-io&phetioStandalone&ea&fuzz&memoryLimit=1000
Query: brand=phet-io&phetioStandalone&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: PhET-iO API error:
2. Registered PhetioObject baseline must equal baseline schema to ensure that baseline changes are intentional.
Error: Assertion failed: PhET-iO API error:
2. Registered PhetioObject baseline must equal baseline schema to ensure that baseline changes are intentional.
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/assert/js/assert.js?bust=1584926582760:22:13)
    at PhetioAPIValidation.assertAPIError (https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/tandem/js/phetioAPIValidation.js:277:15)
    at PhetioAPIValidation.onSimStarted (https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/tandem/js/phetioAPIValidation.js:115:14)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/phet-io/js/phetioEngine.js:158:27
    at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/axon/js/TinyEmitter.js:65:53)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/axon/js/Emitter.js:33:29
    at Emitter.execute (https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/axon/js/Action.js:224:18)
    at Emitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/axon/js/Emitter.js:58:19)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/joist/js/Sim.js:842:48
id: Bayes Chrome
Approximately 3/22/2020, 6:33:45 PM
states-of-matter-basics : phet-io-fuzz : require.js : run
https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/states-of-matter-basics/states-of-matter-basics_en.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&brand=phet-io&phetioStandalone&ea&fuzz&memoryLimit=1000
Query: brand=phet-io&phetioStandalone&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: PhET-iO API error:
2. Registered PhetioObject baseline must equal baseline schema to ensure that baseline changes are intentional.
Error: Assertion failed: PhET-iO API error:
2. Registered PhetioObject baseline must equal baseline schema to ensure that baseline changes are intentional.
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/assert/js/assert.js?bust=1584945674210:22:13)
    at PhetioAPIValidation.assertAPIError (https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/tandem/js/phetioAPIValidation.js:277:15)
    at PhetioAPIValidation.onSimStarted (https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/tandem/js/phetioAPIValidation.js:115:14)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/phet-io/js/phetioEngine.js:158:27
    at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/axon/js/TinyEmitter.js:65:53)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/axon/js/Emitter.js:33:29
    at Emitter.execute (https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/axon/js/Action.js:224:18)
    at Emitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/axon/js/Emitter.js:58:19)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/joist/js/Sim.js:842:48
id: Bayes Chrome
Approximately 3/22/2020, 6:33:45 PM
states-of-matter-basics : phet-io-fuzz : require.js : run
https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/states-of-matter-basics/states-of-matter-basics_en.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&brand=phet-io&phetioStandalone&ea&fuzz&memoryLimit=1000
Query: brand=phet-io&phetioStandalone&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: PhET-iO API error:
2. Registered PhetioObject baseline must equal baseline schema to ensure that baseline changes are intentional.
Error: Assertion failed: PhET-iO API error:
2. Registered PhetioObject baseline must equal baseline schema to ensure that baseline changes are intentional.
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/assert/js/assert.js?bust=1584966797562:22:13)
    at PhetioAPIValidation.assertAPIError (https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/tandem/js/phetioAPIValidation.js:277:15)
    at PhetioAPIValidation.onSimStarted (https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/tandem/js/phetioAPIValidation.js:115:14)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/phet-io/js/phetioEngine.js:158:27
    at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/axon/js/TinyEmitter.js:65:53)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/axon/js/Emitter.js:33:29
    at Emitter.execute (https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/axon/js/Action.js:224:18)
    at Emitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/axon/js/Emitter.js:58:19)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/joist/js/Sim.js:842:48
id: Bayes Chrome
Approximately 3/22/2020, 6:33:45 PM
states-of-matter-basics : phet-io-mirror-inputs-fuzz : require.js : run
https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/phet-io-wrappers/mirror-inputs/?sim=states-of-matter-basics&phetioDebug&fuzz&postMessageToParent&postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload
Uncaught Error: Uncaught Error: Assertion failed: PhET-iO API error:
2. Registered PhetioObject baseline must equal baseline schema to ensure that baseline changes are intentional.
Error: Assertion failed: PhET-iO API error:
2. Registered PhetioObject baseline must equal baseline schema to ensure that baseline changes are intentional.
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/assert/js/assert.js?bust=1584927565016:22:13)
    at PhetioAPIValidation.assertAPIError (https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/tandem/js/phetioAPIValidation.js:277:15)
    at PhetioAPIValidation.onSimStarted (https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/tandem/js/phetioAPIValidation.js:115:14)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/phet-io/js/phetioEngine.js:158:27
    at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/axon/js/TinyEmitter.js:65:53)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/axon/js/Emitter.js:33:29
    at Emitter.execute (https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/axon/js/Action.js:224:18)
    at Emitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/axon/js/Emitter.js:58:19)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/joist/js/Sim.js:842:48
id: Bayes Chrome
Approximately 3/22/2020, 6:33:45 PM
states-of-matter-basics : phet-io-mirror-inputs-fuzz : require.js : run
https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/phet-io-wrappers/mirror-inputs/?sim=states-of-matter-basics&phetioDebug&fuzz&postMessageToParent&postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload
Uncaught Error: Uncaught Error: Assertion failed: PhET-iO API error:
2. Registered PhetioObject baseline must equal baseline schema to ensure that baseline changes are intentional.
Error: Assertion failed: PhET-iO API error:
2. Registered PhetioObject baseline must equal baseline schema to ensure that baseline changes are intentional.
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/assert/js/assert.js?bust=1584949156968:22:13)
    at PhetioAPIValidation.assertAPIError (https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/tandem/js/phetioAPIValidation.js:277:15)
    at PhetioAPIValidation.onSimStarted (https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/tandem/js/phetioAPIValidation.js:115:14)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/phet-io/js/phetioEngine.js:158:27
    at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/axon/js/TinyEmitter.js:65:53)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/axon/js/Emitter.js:33:29
    at Emitter.execute (https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/axon/js/Action.js:224:18)
    at Emitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/axon/js/Emitter.js:58:19)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/joist/js/Sim.js:842:48
id: Bayes Chrome
Approximately 3/22/2020, 6:33:45 PM
states-of-matter-basics : phet-io-mirror-inputs-fuzz : require.js : run
https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/phet-io-wrappers/mirror-inputs/?sim=states-of-matter-basics&phetioDebug&fuzz&postMessageToParent&postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload
Uncaught Error: Uncaught Error: Assertion failed: PhET-iO API error:
2. Registered PhetioObject baseline must equal baseline schema to ensure that baseline changes are intentional.
Error: Assertion failed: PhET-iO API error:
2. Registered PhetioObject baseline must equal baseline schema to ensure that baseline changes are intentional.
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/assert/js/assert.js?bust=1584970384488:22:13)
    at PhetioAPIValidation.assertAPIError (https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/tandem/js/phetioAPIValidation.js:277:15)
    at PhetioAPIValidation.onSimStarted (https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/tandem/js/phetioAPIValidation.js:115:14)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/phet-io/js/phetioEngine.js:158:27
    at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/axon/js/TinyEmitter.js:65:53)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/axon/js/Emitter.js:33:29
    at Emitter.execute (https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/axon/js/Action.js:224:18)
    at Emitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/axon/js/Emitter.js:58:19)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/joist/js/Sim.js:842:48
id: Bayes Chrome
Approximately 3/22/2020, 6:33:45 PM
states-of-matter-basics : phet-io-state-fuzz : require.js : run
https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/phet-io-wrappers/state/?sim=states-of-matter-basics&phetioDebug&fuzz&postMessageToParent&postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload
Uncaught Error: Uncaught Error: Assertion failed: PhET-iO API error:
2. Registered PhetioObject baseline must equal baseline schema to ensure that baseline changes are intentional.
Error: Assertion failed: PhET-iO API error:
2. Registered PhetioObject baseline must equal baseline schema to ensure that baseline changes are intentional.
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/assert/js/assert.js?bust=1584928670214:22:13)
    at PhetioAPIValidation.assertAPIError (https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/tandem/js/phetioAPIValidation.js:277:15)
    at PhetioAPIValidation.onSimStarted (https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/tandem/js/phetioAPIValidation.js:115:14)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/phet-io/js/phetioEngine.js:158:27
    at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/axon/js/TinyEmitter.js:65:53)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/axon/js/Emitter.js:33:29
    at Emitter.execute (https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/axon/js/Action.js:224:18)
    at Emitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/axon/js/Emitter.js:58:19)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/joist/js/Sim.js:842:48
id: Bayes Chrome
Approximately 3/22/2020, 6:33:45 PM
states-of-matter-basics : phet-io-state-fuzz : require.js : run
https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/phet-io-wrappers/state/?sim=states-of-matter-basics&phetioDebug&fuzz&postMessageToParent&postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload
Uncaught Error: Uncaught Error: Assertion failed: PhET-iO API error:
2. Registered PhetioObject baseline must equal baseline schema to ensure that baseline changes are intentional.
Error: Assertion failed: PhET-iO API error:
2. Registered PhetioObject baseline must equal baseline schema to ensure that baseline changes are intentional.
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/assert/js/assert.js?bust=1584940513467:22:13)
    at PhetioAPIValidation.assertAPIError (https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/tandem/js/phetioAPIValidation.js:277:15)
    at PhetioAPIValidation.onSimStarted (https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/tandem/js/phetioAPIValidation.js:115:14)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/phet-io/js/phetioEngine.js:158:27
    at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/axon/js/TinyEmitter.js:65:53)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/axon/js/Emitter.js:33:29
    at Emitter.execute (https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/axon/js/Action.js:224:18)
    at Emitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/axon/js/Emitter.js:58:19)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/joist/js/Sim.js:842:48
id: Bayes Chrome
Approximately 3/22/2020, 6:33:45 PM
states-of-matter-basics : phet-io-state-fuzz : require.js : run
https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/phet-io-wrappers/state/?sim=states-of-matter-basics&phetioDebug&fuzz&postMessageToParent&postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload
Uncaught Error: Uncaught Error: Assertion failed: PhET-iO API error:
2. Registered PhetioObject baseline must equal baseline schema to ensure that baseline changes are intentional.
Error: Assertion failed: PhET-iO API error:
2. Registered PhetioObject baseline must equal baseline schema to ensure that baseline changes are intentional.
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/assert/js/assert.js?bust=1584967463108:22:13)
    at PhetioAPIValidation.assertAPIError (https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/tandem/js/phetioAPIValidation.js:277:15)
    at PhetioAPIValidation.onSimStarted (https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/tandem/js/phetioAPIValidation.js:115:14)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/phet-io/js/phetioEngine.js:158:27
    at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/axon/js/TinyEmitter.js:65:53)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/axon/js/Emitter.js:33:29
    at Emitter.execute (https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/axon/js/Action.js:224:18)
    at Emitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/axon/js/Emitter.js:58:19)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/joist/js/Sim.js:842:48
id: Bayes Chrome
Approximately 3/22/2020, 6:33:45 PM
states-of-matter-basics : phet-io-studio-fuzz : require.js : run
https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/studio/?sim=states-of-matter-basics&phetioDebug&fuzz&postMessageToParent&postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload
Uncaught Error: Uncaught Error: Assertion failed: PhET-iO API error:
2. Registered PhetioObject baseline must equal baseline schema to ensure that baseline changes are intentional.
Error: Assertion failed: PhET-iO API error:
2. Registered PhetioObject baseline must equal baseline schema to ensure that baseline changes are intentional.
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/assert/js/assert.js?bust=1584939559825:22:13)
    at PhetioAPIValidation.assertAPIError (https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/tandem/js/phetioAPIValidation.js:277:15)
    at PhetioAPIValidation.onSimStarted (https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/tandem/js/phetioAPIValidation.js:115:14)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/phet-io/js/phetioEngine.js:158:27
    at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/axon/js/TinyEmitter.js:65:53)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/axon/js/Emitter.js:33:29
    at Emitter.execute (https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/axon/js/Action.js:224:18)
    at Emitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/axon/js/Emitter.js:58:19)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/joist/js/Sim.js:842:48
id: Bayes Chrome
Approximately 3/22/2020, 6:33:45 PM
states-of-matter-basics : phet-io-studio-fuzz : require.js : run
https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/studio/?sim=states-of-matter-basics&phetioDebug&fuzz&postMessageToParent&postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload
Uncaught Error: Uncaught Error: Assertion failed: PhET-iO API error:
2. Registered PhetioObject baseline must equal baseline schema to ensure that baseline changes are intentional.
Error: Assertion failed: PhET-iO API error:
2. Registered PhetioObject baseline must equal baseline schema to ensure that baseline changes are intentional.
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/assert/js/assert.js?bust=1584952208642:22:13)
    at PhetioAPIValidation.assertAPIError (https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/tandem/js/phetioAPIValidation.js:277:15)
    at PhetioAPIValidation.onSimStarted (https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/tandem/js/phetioAPIValidation.js:115:14)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/phet-io/js/phetioEngine.js:158:27
    at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/axon/js/TinyEmitter.js:65:53)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/axon/js/Emitter.js:33:29
    at Emitter.execute (https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/axon/js/Action.js:224:18)
    at Emitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/axon/js/Emitter.js:58:19)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/joist/js/Sim.js:842:48
id: Bayes Chrome
Approximately 3/22/2020, 6:33:45 PM
states-of-matter-basics : phet-io-studio-fuzz : require.js : run
https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/studio/?sim=states-of-matter-basics&phetioDebug&fuzz&postMessageToParent&postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload
Uncaught Error: Uncaught Error: Assertion failed: PhET-iO API error:
2. Registered PhetioObject baseline must equal baseline schema to ensure that baseline changes are intentional.
Error: Assertion failed: PhET-iO API error:
2. Registered PhetioObject baseline must equal baseline schema to ensure that baseline changes are intentional.
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/assert/js/assert.js?bust=1584967286740:22:13)
    at PhetioAPIValidation.assertAPIError (https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/tandem/js/phetioAPIValidation.js:277:15)
    at PhetioAPIValidation.onSimStarted (https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/tandem/js/phetioAPIValidation.js:115:14)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/phet-io/js/phetioEngine.js:158:27
    at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/axon/js/TinyEmitter.js:65:53)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/axon/js/Emitter.js:33:29
    at Emitter.execute (https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/axon/js/Action.js:224:18)
    at Emitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/axon/js/Emitter.js:58:19)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/joist/js/Sim.js:842:48
id: Bayes Chrome
Approximately 3/22/2020, 6:33:45 PM
```

**Comment by chrisklus** [comment]
Thanks @KatieWoe. CT is clear, closing.
