### ISSUE TITLE
CT statesOfMatterBasics.phaseChangesScreen.view.pressureMeter

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/states-of-matter-basics#26]
```
states-of-matter-basics : phet-io-fuzz : require.js : load
https://bayes.colorado.edu/continuous-testing/snapshot-1585872107151/states-of-matter-basics/states-of-matter-basics_en.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&brand=phet-io&phetioStandalone&ea&fuzz&memoryLimit=1000
Query: brand=phet-io&phetioStandalone&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: PhET-iO API error:
statesOfMatterBasics.phaseChangesScreen.view.pressureMeter:  5. When the sim is finished starting up, all non-dynamic schema entries must be registered.
Error: Assertion failed: PhET-iO API error:
statesOfMatterBasics.phaseChangesScreen.view.pressureMeter:  5. When the sim is finished starting up, all non-dynamic schema entries must be registered.
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1585872107151/assert/js/assert.js?bust=1585891540206:22:13)
    at PhetioAPIValidation.assertAPIError (https://bayes.colorado.edu/continuous-testing/snapshot-1585872107151/tandem/js/phetioAPIValidation.js:278:15)
    at PhetioAPIValidation.onSimStarted (https://bayes.colorado.edu/continuous-testing/snapshot-1585872107151/tandem/js/phetioAPIValidation.js:107:16)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1585872107151/phet-io/js/phetioEngine.js:158:29
    at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1585872107151/axon/js/TinyEmitter.js:65:53)
    at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1585872107151/axon/js/Property.js:276:25)
    at Property.set (https://bayes.colorado.edu/continuous-testing/snapshot-1585872107151/axon/js/Property.js:175:14)
    at Property.set value [as value] (https://bayes.colorado.edu/continuous-testing/snapshot-1585872107151/axon/js/Property.js:346:32)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1585872107151/joist/js/Sim.js:845:57
id: Bayes Chrome
Approximately 4/2/2020, 6:01:47 PM
states-of-matter-basics : phet-io-fuzz : require.js : load
https://bayes.colorado.edu/continuous-testing/snapshot-1585872107151/states-of-matter-basics/states-of-matter-basics_en.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&brand=phet-io&phetioStandalone&ea&fuzz&memoryLimit=1000
Query: brand=phet-io&phetioStandalone&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: PhET-iO API error:
statesOfMatterBasics.phaseChangesScreen.view.pressureMeter:  5. When the sim is finished starting up, all non-dynamic schema entries must be registered.
Error: Assertion failed: PhET-iO API error:
statesOfMatterBasics.phaseChangesScreen.view.pressureMeter:  5. When the sim is finished starting up, all non-dynamic schema entries must be registered.
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1585872107151/assert/js/assert.js?bust=1585902057601:22:13)
    at PhetioAPIValidation.assertAPIError (https://bayes.colorado.edu/continuous-testing/snapshot-1585872107151/tandem/js/phetioAPIValidation.js:278:15)
    at PhetioAPIValidation.onSimStarted (https://bayes.colorado.edu/continuous-testing/snapshot-1585872107151/tandem/js/phetioAPIValidation.js:107:16)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1585872107151/phet-io/js/phetioEngine.js:158:29
    at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1585872107151/axon/js/TinyEmitter.js:65:53)
    at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1585872107151/axon/js/Property.js:276:25)
    at Property.set (https://bayes.colorado.edu/continuous-testing/snapshot-1585872107151/axon/js/Property.js:175:14)
    at Property.set value [as value] (https://bayes.colorado.edu/continuous-testing/snapshot-1585872107151/axon/js/Property.js:346:32)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1585872107151/joist/js/Sim.js:845:57
id: Bayes Chrome
Approximately 4/2/2020, 6:01:47 PM
states-of-matter-basics : phet-io-fuzz : require.js : run
https://bayes.colorado.edu/continuous-testing/snapshot-1585872107151/states-of-matter-basics/states-of-matter-basics_en.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&brand=phet-io&phetioStandalone&ea&fuzz&memoryLimit=1000
Query: brand=phet-io&phetioStandalone&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: PhET-iO API error:
statesOfMatterBasics.phaseChangesScreen.view.pressureMeter:  5. When the sim is finished starting up, all non-dynamic schema entries must be registered.
Error: Assertion failed: PhET-iO API error:
statesOfMatterBasics.phaseChangesScreen.view.pressureMeter:  5. When the sim is finished starting up, all non-dynamic schema entries must be registered.
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1585872107151/assert/js/assert.js?bust=1585891540206:22:13)
    at PhetioAPIValidation.assertAPIError (https://bayes.colorado.edu/continuous-testing/snapshot-1585872107151/tandem/js/phetioAPIValidation.js:278:15)
    at PhetioAPIValidation.onSimStarted (https://bayes.colorado.edu/continuous-testing/snapshot-1585872107151/tandem/js/phetioAPIValidation.js:107:16)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1585872107151/phet-io/js/phetioEngine.js:158:29
    at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1585872107151/axon/js/TinyEmitter.js:65:53)
    at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1585872107151/axon/js/Property.js:276:25)
    at Property.set (https://bayes.colorado.edu/continuous-testing/snapshot-1585872107151/axon/js/Property.js:175:14)
    at Property.set value [as value] (https://bayes.colorado.edu/continuous-testing/snapshot-1585872107151/axon/js/Property.js:346:32)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1585872107151/joist/js/Sim.js:845:57
id: Bayes Chrome
Approximately 4/2/2020, 6:01:47 PM
states-of-matter-basics : phet-io-fuzz : require.js : run
https://bayes.colorado.edu/continuous-testing/snapshot-1585872107151/states-of-matter-basics/states-of-matter-basics_en.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&brand=phet-io&phetioStandalone&ea&fuzz&memoryLimit=1000
Query: brand=phet-io&phetioStandalone&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: PhET-iO API error:
statesOfMatterBasics.phaseChangesScreen.view.pressureMeter:  5. When the sim is finished starting up, all non-dynamic schema entries must be registered.
Error: Assertion failed: PhET-iO API error:
statesOfMatterBasics.phaseChangesScreen.view.pressureMeter:  5. When the sim is finished starting up, all non-dynamic schema entries must be registered.
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1585872107151/assert/js/assert.js?bust=1585902057601:22:13)
    at PhetioAPIValidation.assertAPIError (https://bayes.colorado.edu/continuous-testing/snapshot-1585872107151/tandem/js/phetioAPIValidation.js:278:15)
    at PhetioAPIValidation.onSimStarted (https://bayes.colorado.edu/continuous-testing/snapshot-1585872107151/tandem/js/phetioAPIValidation.js:107:16)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1585872107151/phet-io/js/phetioEngine.js:158:29
    at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1585872107151/axon/js/TinyEmitter.js:65:53)
    at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1585872107151/axon/js/Property.js:276:25)
    at Property.set (https://bayes.colorado.edu/continuous-testing/snapshot-1585872107151/axon/js/Property.js:175:14)
    at Property.set value [as value] (https://bayes.colorado.edu/continuous-testing/snapshot-1585872107151/axon/js/Property.js:346:32)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1585872107151/joist/js/Sim.js:845:57
id: Bayes Chrome
Approximately 4/2/2020, 6:01:47 PM
states-of-matter-basics : phet-io-mirror-inputs-fuzz : require.js : run
https://bayes.colorado.edu/continuous-testing/snapshot-1585872107151/phet-io-wrappers/mirror-inputs/?sim=states-of-matter-basics&phetioDebug&fuzz&postMessageToParent&postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload
Uncaught Error: Uncaught Error: Assertion failed: PhET-iO API error:
statesOfMatterBasics.phaseChangesScreen.view.pressureMeter:  5. When the sim is finished starting up, all non-dynamic schema entries must be registered.
Error: Assertion failed: PhET-iO API error:
statesOfMatterBasics.phaseChangesScreen.view.pressureMeter:  5. When the sim is finished starting up, all non-dynamic schema entries must be registered.
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1585872107151/assert/js/assert.js?bust=1585875813377:22:13)
    at PhetioAPIValidation.assertAPIError (https://bayes.colorado.edu/continuous-testing/snapshot-1585872107151/tandem/js/phetioAPIValidation.js:278:15)
    at PhetioAPIValidation.onSimStarted (https://bayes.colorado.edu/continuous-testing/snapshot-1585872107151/tandem/js/phetioAPIValidation.js:107:16)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1585872107151/phet-io/js/phetioEngine.js:158:29
    at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1585872107151/axon/js/TinyEmitter.js:65:53)
    at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1585872107151/axon/js/Property.js:276:25)
    at Property.set (https://bayes.colorado.edu/continuous-testing/snapshot-1585872107151/axon/js/Property.js:175:14)
    at Property.set value [as value] (https://bayes.colorado.edu/continuous-testing/snapshot-1585872107151/axon/js/Property.js:346:32)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1585872107151/joist/js/Sim.js:845:57
id: Bayes Chrome
Approximately 4/2/2020, 6:01:47 PM
states-of-matter-basics : phet-io-mirror-inputs-fuzz : require.js : run
https://bayes.colorado.edu/continuous-testing/snapshot-1585872107151/phet-io-wrappers/mirror-inputs/?sim=states-of-matter-basics&phetioDebug&fuzz&postMessageToParent&postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload
Uncaught Error: Uncaught Error: Assertion failed: PhET-iO API error:
statesOfMatterBasics.phaseChangesScreen.view.pressureMeter:  5. When the sim is finished starting up, all non-dynamic schema entries must be registered.
Error: Assertion failed: PhET-iO API error:
statesOfMatterBasics.phaseChangesScreen.view.pressureMeter:  5. When the sim is finished starting up, all non-dynamic schema entries must be registered.
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1585872107151/assert/js/assert.js?bust=1585892411933:22:13)
    at PhetioAPIValidation.assertAPIError (https://bayes.colorado.edu/continuous-testing/snapshot-1585872107151/tandem/js/phetioAPIValidation.js:278:15)
    at PhetioAPIValidation.onSimStarted (https://bayes.colorado.edu/continuous-testing/snapshot-1585872107151/tandem/js/phetioAPIValidation.js:107:16)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1585872107151/phet-io/js/phetioEngine.js:158:29
    at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1585872107151/axon/js/TinyEmitter.js:65:53)
    at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1585872107151/axon/js/Property.js:276:25)
    at Property.set (https://bayes.colorado.edu/continuous-testing/snapshot-1585872107151/axon/js/Property.js:175:14)
    at Property.set value [as value] (https://bayes.colorado.edu/continuous-testing/snapshot-1585872107151/axon/js/Property.js:346:32)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1585872107151/joist/js/Sim.js:845:57
id: Bayes Chrome
Approximately 4/2/2020, 6:01:47 PM
states-of-matter-basics : phet-io-state-fuzz : require.js : run
https://bayes.colorado.edu/continuous-testing/snapshot-1585872107151/phet-io-wrappers/state/?sim=states-of-matter-basics&phetioDebug&fuzz&postMessageToParent&postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload
Uncaught Error: Uncaught Error: Assertion failed: PhET-iO API error:
statesOfMatterBasics.phaseChangesScreen.view.pressureMeter:  5. When the sim is finished starting up, all non-dynamic schema entries must be registered.
Error: Assertion failed: PhET-iO API error:
statesOfMatterBasics.phaseChangesScreen.view.pressureMeter:  5. When the sim is finished starting up, all non-dynamic schema entries must be registered.
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1585872107151/assert/js/assert.js?bust=1585880100656:22:13)
    at PhetioAPIValidation.assertAPIError (https://bayes.colorado.edu/continuous-testing/snapshot-1585872107151/tandem/js/phetioAPIValidation.js:278:15)
    at PhetioAPIValidation.onSimStarted (https://bayes.colorado.edu/continuous-testing/snapshot-1585872107151/tandem/js/phetioAPIValidation.js:107:16)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1585872107151/phet-io/js/phetioEngine.js:158:29
    at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1585872107151/axon/js/TinyEmitter.js:65:53)
    at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1585872107151/axon/js/Property.js:276:25)
    at Property.set (https://bayes.colorado.edu/continuous-testing/snapshot-1585872107151/axon/js/Property.js:175:14)
    at Property.set value [as value] (https://bayes.colorado.edu/continuous-testing/snapshot-1585872107151/axon/js/Property.js:346:32)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1585872107151/joist/js/Sim.js:845:57
id: Bayes Chrome
Approximately 4/2/2020, 6:01:47 PM
states-of-matter-basics : phet-io-studio-fuzz : require.js : run
https://bayes.colorado.edu/continuous-testing/snapshot-1585872107151/studio/?sim=states-of-matter-basics&phetioDebug&fuzz&postMessageToParent&postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload
Uncaught Error: Uncaught Error: Assertion failed: PhET-iO API error:
statesOfMatterBasics.phaseChangesScreen.view.pressureMeter:  5. When the sim is finished starting up, all non-dynamic schema entries must be registered.
Error: Assertion failed: PhET-iO API error:
statesOfMatterBasics.phaseChangesScreen.view.pressureMeter:  5. When the sim is finished starting up, all non-dynamic schema entries must be registered.
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1585872107151/assert/js/assert.js?bust=1585878831951:22:13)
    at PhetioAPIValidation.assertAPIError (https://bayes.colorado.edu/continuous-testing/snapshot-1585872107151/tandem/js/phetioAPIValidation.js:278:15)
    at PhetioAPIValidation.onSimStarted (https://bayes.colorado.edu/continuous-testing/snapshot-1585872107151/tandem/js/phetioAPIValidation.js:107:16)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1585872107151/phet-io/js/phetioEngine.js:158:29
    at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1585872107151/axon/js/TinyEmitter.js:65:53)
    at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1585872107151/axon/js/Property.js:276:25)
    at Property.set (https://bayes.colorado.edu/continuous-testing/snapshot-1585872107151/axon/js/Property.js:175:14)
    at Property.set value [as value] (https://bayes.colorado.edu/continuous-testing/snapshot-1585872107151/axon/js/Property.js:346:32)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1585872107151/joist/js/Sim.js:845:57
id: Bayes Chrome
Approximately 4/2/2020, 6:01:47 PM
states-of-matter-basics : phet-io-studio-fuzz : require.js : run
https://bayes.colorado.edu/continuous-testing/snapshot-1585872107151/studio/?sim=states-of-matter-basics&phetioDebug&fuzz&postMessageToParent&postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload
Uncaught Error: Uncaught Error: Assertion failed: PhET-iO API error:
statesOfMatterBasics.phaseChangesScreen.view.pressureMeter:  5. When the sim is finished starting up, all non-dynamic schema entries must be registered.
Error: Assertion failed: PhET-iO API error:
statesOfMatterBasics.phaseChangesScreen.view.pressureMeter:  5. When the sim is finished starting up, all non-dynamic schema entries must be registered.
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1585872107151/assert/js/assert.js?bust=1585904798596:22:13)
    at PhetioAPIValidation.assertAPIError (https://bayes.colorado.edu/continuous-testing/snapshot-1585872107151/tandem/js/phetioAPIValidation.js:278:15)
    at PhetioAPIValidation.onSimStarted (https://bayes.colorado.edu/continuous-testing/snapshot-1585872107151/tandem/js/phetioAPIValidation.js:107:16)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1585872107151/phet-io/js/phetioEngine.js:158:29
    at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1585872107151/axon/js/TinyEmitter.js:65:53)
    at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1585872107151/axon/js/Property.js:276:25)
    at Property.set (https://bayes.colorado.edu/continuous-testing/snapshot-1585872107151/axon/js/Property.js:175:14)
    at Property.set value [as value] (https://bayes.colorado.edu/continuous-testing/snapshot-1585872107151/axon/js/Property.js:346:32)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1585872107151/joist/js/Sim.js:845:57
id: Bayes Chrome
Approximately 4/2/2020, 6:01:47 PM
```

**Comment by jbphet** [comment]
Fixed by updated API files, CT now looks clear, closing.
