### ISSUE TITLE
CT all non-dynamic schema entries must be registered

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/states-of-matter-basics#27]
```
states-of-matter-basics : phet-io-fuzz : require.js
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1587708955810/states-of-matter-basics/states-of-matter-basics_en.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&brand=phet-io&phetioStandalone&ea&phetioValidateTandems&fuzz&memoryLimit=1000
Query: brand=phet-io&phetioStandalone&ea&phetioValidateTandems&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: PhET-iO API error:
statesOfMatterBasics.phaseChangesScreen.model.numberOfMoleculesProperty:  5. When the sim is finished starting up, all non-dynamic schema entries must be registered.
Error: Assertion failed: PhET-iO API error:
statesOfMatterBasics.phaseChangesScreen.model.numberOfMoleculesProperty:  5. When the sim is finished starting up, all non-dynamic schema entries must be registered.
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1587708955810/assert/js/assert.js:22:13)
    at PhetioAPIValidation.assertAPIError (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1587708955810/tandem/js/phetioAPIValidation.js:278:15)
    at PhetioAPIValidation.onSimStarted (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1587708955810/tandem/js/phetioAPIValidation.js:107:16)
    at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1587708955810/phet-io/js/phetioEngine.js:158:29
    at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1587708955810/axon/js/TinyEmitter.js:69:53)
    at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1587708955810/axon/js/Property.js:270:25)
    at Property.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1587708955810/axon/js/Property.js:170:14)
    at Property.set value [as value] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1587708955810/axon/js/Property.js:340:32)
    at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1587708955810/joist/js/Sim.js:851:57
id: Bayes Chrome

states-of-matter-basics : phet-io-mirror-inputs-fuzz : require.js
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1587708955810/phet-io-wrappers/mirror-inputs/?sim=states-of-matter-basics&phetioDebug&fuzz&postMessageToParent&postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload
Uncaught Error: Uncaught Error: Assertion failed: PhET-iO API error:
statesOfMatterBasics.phaseChangesScreen.model.numberOfMoleculesProperty:  5. When the sim is finished starting up, all non-dynamic schema entries must be registered.
Error: Assertion failed: PhET-iO API error:
statesOfMatterBasics.phaseChangesScreen.model.numberOfMoleculesProperty:  5. When the sim is finished starting up, all non-dynamic schema entries must be registered.
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1587708955810/assert/js/assert.js:22:13)
    at PhetioAPIValidation.assertAPIError (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1587708955810/tandem/js/phetioAPIValidation.js:278:15)
    at PhetioAPIValidation.onSimStarted (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1587708955810/tandem/js/phetioAPIValidation.js:107:16)
    at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1587708955810/phet-io/js/phetioEngine.js:158:29
    at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1587708955810/axon/js/TinyEmitter.js:69:53)
    at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1587708955810/axon/js/Property.js:270:25)
    at Property.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1587708955810/axon/js/Property.js:170:14)
    at Property.set value [as value] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1587708955810/axon/js/Property.js:340:32)
    at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1587708955810/joist/js/Sim.js:851:57
id: Bayes Chrome

states-of-matter-basics : phet-io-state-fuzz : require.js
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1587708955810/phet-io-wrappers/state/?sim=states-of-matter-basics&phetioDebug&fuzz&postMessageToParent&postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload
Uncaught Error: Uncaught Error: Assertion failed: PhET-iO API error:
statesOfMatterBasics.phaseChangesScreen.model.numberOfMoleculesProperty:  5. When the sim is finished starting up, all non-dynamic schema entries must be registered.
Error: Assertion failed: PhET-iO API error:
statesOfMatterBasics.phaseChangesScreen.model.numberOfMoleculesProperty:  5. When the sim is finished starting up, all non-dynamic schema entries must be registered.
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1587708955810/assert/js/assert.js:22:13)
    at PhetioAPIValidation.assertAPIError (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1587708955810/tandem/js/phetioAPIValidation.js:278:15)
    at PhetioAPIValidation.onSimStarted (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1587708955810/tandem/js/phetioAPIValidation.js:107:16)
    at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1587708955810/phet-io/js/phetioEngine.js:158:29
    at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1587708955810/axon/js/TinyEmitter.js:69:53)
    at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1587708955810/axon/js/Property.js:270:25)
    at Property.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1587708955810/axon/js/Property.js:170:14)
    at Property.set value [as value] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1587708955810/axon/js/Property.js:340:32)
    at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1587708955810/joist/js/Sim.js:851:57
id: Bayes Chrome

states-of-matter-basics : phet-io-studio-fuzz : require.js
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1587708955810/studio/?sim=states-of-matter-basics&phetioDebug&fuzz&postMessageToParent&postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload
Uncaught Error: Uncaught Error: Assertion failed: PhET-iO API error:
statesOfMatterBasics.phaseChangesScreen.model.numberOfMoleculesProperty:  5. When the sim is finished starting up, all non-dynamic schema entries must be registered.
Error: Assertion failed: PhET-iO API error:
statesOfMatterBasics.phaseChangesScreen.model.numberOfMoleculesProperty:  5. When the sim is finished starting up, all non-dynamic schema entries must be registered.
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1587708955810/assert/js/assert.js:22:13)
    at PhetioAPIValidation.assertAPIError (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1587708955810/tandem/js/phetioAPIValidation.js:278:15)
    at PhetioAPIValidation.onSimStarted (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1587708955810/tandem/js/phetioAPIValidation.js:107:16)
    at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1587708955810/phet-io/js/phetioEngine.js:158:29
    at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1587708955810/axon/js/TinyEmitter.js:69:53)
    at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1587708955810/axon/js/Property.js:270:25)
    at Property.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1587708955810/axon/js/Property.js:170:14)
    at Property.set value [as value] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1587708955810/axon/js/Property.js:340:32)
    at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1587708955810/joist/js/Sim.js:851:57
id: Bayes Chrome
```

**Comment by jbphet** [comment]
I updated the API files and CT has been clear for a while.  Closing.
