### ISSUE TITLE
CT Any schema entries in the overrides file must be different from its baseline counterpart

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/states-of-matter-basics#28]
```
states-of-matter-basics : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593515345795/states-of-matter-basics/states-of-matter-basics_en.html?continuousTest=%7B%22test%22%3A%5B%22states-of-matter-basics%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1593515345795%22%2C%22timestamp%22%3A1593517971437%7D&brand=phet-io&phetioStandalone&ea&phetioValidateTandems&fuzz&memoryLimit=1000
Query: brand=phet-io&phetioStandalone&ea&phetioValidateTandems&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: PhET-iO API error:
statesOfMatterBasics.statesScreen.model.isPlayingProperty: 8. Any schema entries in the overrides file must be different from its baseline counterpart.
Error: Assertion failed: PhET-iO API error:
statesOfMatterBasics.statesScreen.model.isPlayingProperty: 8. Any schema entries in the overrides file must be different from its baseline counterpart.
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593515345795/assert/js/assert.js:22:13)
at PhetioAPIValidation.assertAPIError (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593515345795/tandem/js/phetioAPIValidation.js:358:15)
at PhetioAPIValidation.validateOverridesFile (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593515345795/tandem/js/phetioAPIValidation.js:335:20)
at PhetioAPIValidation.onSimStarted (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593515345795/tandem/js/phetioAPIValidation.js:109:10)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593515345795/phet-io/js/phetioEngine.js:183:29
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593515345795/axon/js/TinyEmitter.js:69:53)
at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593515345795/axon/js/Property.js:273:25)
at Property.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593515345795/axon/js/Property.js:171:14)
at Property.set value [as value] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593515345795/axon/js/Property.js:345:32)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593515345795/joist/js/Sim.js:856:57
id: Bayes Chrome
Snapshot from 6/30/2020, 5:09:05 AM

----------------------------------

states-of-matter-basics : phet-io-mirror-inputs-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593515345795/phet-io-wrappers/mirror-inputs/?sim=states-of-matter-basics&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22states-of-matter-basics%22%2C%22phet-io-mirror-inputs-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1593515345795%22%2C%22timestamp%22%3A1593517501471%7D
Uncaught Error: Uncaught Error: Assertion failed: PhET-iO API error:
statesOfMatterBasics.statesScreen.model.isPlayingProperty: 8. Any schema entries in the overrides file must be different from its baseline counterpart.
Error: Assertion failed: PhET-iO API error:
statesOfMatterBasics.statesScreen.model.isPlayingProperty: 8. Any schema entries in the overrides file must be different from its baseline counterpart.
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593515345795/assert/js/assert.js:22:13)
at PhetioAPIValidation.assertAPIError (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593515345795/tandem/js/phetioAPIValidation.js:358:15)
at PhetioAPIValidation.validateOverridesFile (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593515345795/tandem/js/phetioAPIValidation.js:335:20)
at PhetioAPIValidation.onSimStarted (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593515345795/tandem/js/phetioAPIValidation.js:109:10)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593515345795/phet-io/js/phetioEngine.js:183:29
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593515345795/axon/js/TinyEmitter.js:69:53)
at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593515345795/axon/js/Property.js:273:25)
at Property.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593515345795/axon/js/Property.js:171:14)
at Property.set value [as value] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593515345795/axon/js/Property.js:345:32)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593515345795/joist/js/Sim.js:856:57
id: Bayes Chrome
Snapshot from 6/30/2020, 5:09:05 AM

----------------------------------

states-of-matter-basics : phet-io-state-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593515345795/phet-io-wrappers/state/?sim=states-of-matter-basics&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22states-of-matter-basics%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1593515345795%22%2C%22timestamp%22%3A1593520357108%7D
Uncaught Error: Uncaught Error: Assertion failed: PhET-iO API error:
statesOfMatterBasics.statesScreen.model.isPlayingProperty: 8. Any schema entries in the overrides file must be different from its baseline counterpart.
Error: Assertion failed: PhET-iO API error:
statesOfMatterBasics.statesScreen.model.isPlayingProperty: 8. Any schema entries in the overrides file must be different from its baseline counterpart.
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593515345795/assert/js/assert.js:22:13)
at PhetioAPIValidation.assertAPIError (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593515345795/tandem/js/phetioAPIValidation.js:358:15)
at PhetioAPIValidation.validateOverridesFile (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593515345795/tandem/js/phetioAPIValidation.js:335:20)
at PhetioAPIValidation.onSimStarted (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593515345795/tandem/js/phetioAPIValidation.js:109:10)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593515345795/phet-io/js/phetioEngine.js:183:29
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593515345795/axon/js/TinyEmitter.js:69:53)
at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593515345795/axon/js/Property.js:273:25)
at Property.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593515345795/axon/js/Property.js:171:14)
at Property.set value [as value] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593515345795/axon/js/Property.js:345:32)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593515345795/joist/js/Sim.js:856:57
id: Bayes Chrome
Snapshot from 6/30/2020, 5:09:05 AM

----------------------------------

states-of-matter-basics : phet-io-studio-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593515345795/studio/?sim=states-of-matter-basics&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22states-of-matter-basics%22%2C%22phet-io-studio-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1593515345795%22%2C%22timestamp%22%3A1593517849120%7D
Uncaught Error: Uncaught Error: Assertion failed: PhET-iO API error:
statesOfMatterBasics.statesScreen.model.isPlayingProperty: 8. Any schema entries in the overrides file must be different from its baseline counterpart.
Error: Assertion failed: PhET-iO API error:
statesOfMatterBasics.statesScreen.model.isPlayingProperty: 8. Any schema entries in the overrides file must be different from its baseline counterpart.
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593515345795/assert/js/assert.js:22:13)
at PhetioAPIValidation.assertAPIError (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593515345795/tandem/js/phetioAPIValidation.js:358:15)
at PhetioAPIValidation.validateOverridesFile (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593515345795/tandem/js/phetioAPIValidation.js:335:20)
at PhetioAPIValidation.onSimStarted (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593515345795/tandem/js/phetioAPIValidation.js:109:10)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593515345795/phet-io/js/phetioEngine.js:183:29
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593515345795/axon/js/TinyEmitter.js:69:53)
at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593515345795/axon/js/Property.js:273:25)
at Property.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593515345795/axon/js/Property.js:171:14)
at Property.set value [as value] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593515345795/axon/js/Property.js:345:32)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593515345795/joist/js/Sim.js:856:57
id: Bayes Chrome
Snapshot from 6/30/2020, 5:09:05 AM

----------------------------------

states-of-matter-basics : phet-io-wrappers-tests : assert
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593515345795/phet-io-wrappers/phet-io-wrappers-tests.html?sim=states-of-matter-basics&phetioDebug
3 out of 4 tests passed. 1 failed.
SimTests: states-of-matter-basics: iframe api failed:
Uncaught Error: Uncaught Error: Assertion failed: PhET-iO API error:
statesOfMatterBasics.statesScreen.model.isPlayingProperty: 8. Any schema entries in the overrides file must be different from its baseline counterpart.
Error: Assertion failed: PhET-iO API error:
statesOfMatterBasics.statesScreen.model.isPlayingProperty: 8. Any schema entries in the overrides file must be different from its baseline counterpart.
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593515345795/assert/js/assert.js:22:13)
at PhetioAPIValidation.assertAPIError (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593515345795/tandem/js/phetioAPIValidation.js:358:15)
at PhetioAPIValidation.validateOverridesFile (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593515345795/tandem/js/phetioAPIValidation.js:335:20)
at PhetioAPIValidation.onSimStarted (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593515345795/tandem/js/phetioAPIValidation.js:109:10)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593515345795/phet-io/js/phetioEngine.js:183:29
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593515345795/axon/js/TinyEmitter.js:69:53)
at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593515345795/axon/js/Property.js:273:25)
at Property.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593515345795/axon/js/Property.js:171:14)
at Property.set value [as value] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593515345795/axon/js/Property.js:345:32)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593515345795/joist/js/Sim.js:856:57

Did not complete in 200000ms, may not have completed all tests
id: Bayes Chrome
Snapshot from 6/30/2020, 5:09:05 AM

----------------------------------

states-of-matter-basics : phet-io-wrappers-tests : no-assert
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593515345795/phet-io-wrappers/phet-io-wrappers-tests.html?sim=states-of-matter-basics
3 out of 4 tests passed. 1 failed.
SimTests: states-of-matter-basics: iframe api failed:
Uncaught Error: Uncaught Error: Assertion failed: PhET-iO API error:
statesOfMatterBasics.statesScreen.model.isPlayingProperty: 8. Any schema entries in the overrides file must be different from its baseline counterpart.
Error: Assertion failed: PhET-iO API error:
statesOfMatterBasics.statesScreen.model.isPlayingProperty: 8. Any schema entries in the overrides file must be different from its baseline counterpart.
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593515345795/assert/js/assert.js:22:13)
at PhetioAPIValidation.assertAPIError (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593515345795/tandem/js/phetioAPIValidation.js:358:15)
at PhetioAPIValidation.validateOverridesFile (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593515345795/tandem/js/phetioAPIValidation.js:335:20)
at PhetioAPIValidation.onSimStarted (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593515345795/tandem/js/phetioAPIValidation.js:109:10)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593515345795/phet-io/js/phetioEngine.js:183:29
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593515345795/axon/js/TinyEmitter.js:69:53)
at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593515345795/axon/js/Property.js:273:25)
at Property.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593515345795/axon/js/Property.js:171:14)
at Property.set value [as value] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593515345795/axon/js/Property.js:345:32)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593515345795/joist/js/Sim.js:856:57

Did not complete in 200000ms, may not have completed all tests
id: Bayes Chrome
Snapshot from 6/30/2020, 5:09:05 AM
```

**Comment by jbphet** [comment]
Fixed, and CT looks clear.  Closing.
