### ISSUE TITLE
CT ProjectorModeCheckbox requires sims that support projector color profiles

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/states-of-matter-basics#32]
Also happens in atomic interactions
```
states-of-matter-basics : phet-io-mirror-inputs-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1626714668609/phet-io-wrappers/mirror-inputs/?sim=states-of-matter-basics&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22states-of-matter-basics%22%2C%22phet-io-mirror-inputs-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1626714668609%22%2C%22timestamp%22%3A1626716337414%7D
Uncaught Error: Uncaught Error: Assertion failed: ProjectorModeCheckbox requires sims that support projector color profiles and a different primary one
Error: Assertion failed: ProjectorModeCheckbox requires sims that support projector color profiles and a different primary one
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1626714668609/assert/js/assert.js:25:13)
at new ProjectorModeCheckbox (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1626714668609/joist/js/ProjectorModeCheckbox.js:42:15)
at new GlobalOptionsNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1626714668609/states-of-matter/js/common/view/GlobalOptionsNode.js:23:35)
at createOptionsDialogContent (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1626714668609/states-of-matter-basics/js/states-of-matter-basics-main.js:34:43)
at new OptionsDialog (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1626714668609/joist/js/OptionsDialog.js:44:21)
at PhetioCapsule.createElement (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1626714668609/joist/js/PhetMenu.js:120:31)
at PhetioCapsule.createDynamicElement (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1626714668609/tandem/js/PhetioDynamicElementContainer.js:230:32)
at PhetioCapsule.create (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1626714668609/tandem/js/PhetioCapsule.js:106:25)
at PhetioCapsule.getElement (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1626714668609/tandem/js/PhetioCapsule.js:69:12)
at callback (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1626714668609/joist/js/PhetMenu.js:143:46)
id: Bayes Chrome
Snapshot from 7/19/2021, 11:11:08 AM
```

**Comment by jbphet** [comment]
@KatieWoe - I'm not seeing this on CT and am so far unable to duplicate it locally.  I know there was some work going on for color profiles recently.  Do you think this problem was just a short-term side effect of that work?  Can we just close it?

**Comment by KatieWoe** [comment]
It looks like it may have been fixed in ithub.com/phetsims/molecule-shapes/issues/189 closing
